src/Intervals.jl
src/interval.jl
test/interval.jl

Replace `in(::AbstractInterval, ::AbstractInterval)` with `issubset(::AbstractInterval, ::AbstractInterval)` and define/export `⊆`, `⊇`, `⊈`, and `⊉`
Closes #15

Replace `in` with `issubset`

---

src/endpoint.jl
test/endpoint.jl

Verifies that endpoint `==` works. ~I need this~ Used in an upcoming PR.

Endpoint equality

---

src/anchoredinterval.jl

Fixes a bug introduced in #13. I only caught this because of the tests in #8. This fix is also included in that PR.

Fix `<` for `AnchoredInterval`

---

src/anchoredinterval.jl
src/endpoint.jl
src/interval.jl
test/comparisons.jl
test/runtests.jl

A new test suite which performs a variety of comparisons on the various possible kinds of intervals. I found this to be rather useful for catching corner cases as I modified the code.
I've also modified `isless` and `<` to be different. The behaviour of `isless` which is used for sorting just checks the left-endpoint. When the left-endpoints are equal the two intervals are considered equal for sorting and are produced in the order in which they appear.

Interval comparison tests

---

src/anchoredinterval.jl
src/interval.jl
test/anchoredinterval.jl
test/interval.jl

Allows us to easily convert `Interval`s and `AnchoredInterval`s from one time zone to another.

Add astimezone(::Interval{ZonedDateTime}, ::TimeZone)

---

src/description.jl
test/anchoredinterval.jl

Fixes a corner case in `print(::AnchoredInterval{P, ZonedDateTime})` in which the time is omitted, in which case the time zone might be mistaken for the time.
Closes #23

Improve print(::AnchoredInterval{P, ZonedDateTime})

---

docs/src/index.md
src/anchoredinterval.jl
src/interval.jl
test/anchoredinterval.jl
test/comparisons.jl
test/interval.jl

Allows `sort`ing of `AbstractInterval`s.
Closes #19

Replace `<` with `isless`

---

docs/src/index.md

Adds documentation detailing some special considerations to be made when comparing `Interval`s with `AnchoredInterval`s.

Improve docs for equality and DataFrames

---

src/endpoint.jl

In cases where we have `==(LeftEndpoint, LeftEndpoint)` or `==(RightEndpoint, RightEndpoint)` julia was falling back to the `===` check. This passes tests, but causes problems if the addresses are different. This PR simply adds a default `==(Endpoint, Endpoint)` fallback that just checks if the `endpoint` and `included` variables are equal.

Add equality for matching left/right endpoints

---

src/interval.jl

While investigating https://github.com/invenia/Intervals.jl/issues/29 I found a way to slightly improve performance of the inner constructor:
```julia
julia> using Intervals, BenchmarkTools
julia> struct IntervalNoCheck{T} <: AbstractInterval{T}
first::T
last::T
inclusivity::Inclusivity
function IntervalNoCheck{T}(f::T, l::T, inc::Inclusivity) where T
return new(f, l, inc)
end
end
julia> struct IntervalA{T} <: AbstractInterval{T}
first::T
last::T
inclusivity::Inclusivity
function IntervalA{T}(f::T, l::T, inc::Inclusivity) where T
if f > l
f, l = l, f
inc = Inclusivity(last(inc), first(inc))
end
return new(f, l, inc)
end
end
julia> struct IntervalB{T} <: AbstractInterval{T}
first::T
last::T
inclusivity::Inclusivity
function IntervalB{T}(f::T, l::T, inc::Inclusivity) where T
a, b, c = if f …
```

Slightly improve Interval inner constructor speed

---

src/endpoint.jl
test/endpoint.jl

While updating the documentation for `==(::Endpoint, ::Endpoint)` I noticed that the type parameters for the conditionals was unnecessary and would make `Intervals.RightEndpoint(1, true) < Intervals.LeftEndpoint(1.0, false)` result in a `MethodError`. The tests were updated to always use mixed type endpoints.

Remove where from Endpoint comparisons

---

.appveyor.yml
.travis.yml
REQUIRE
src/Intervals.jl
src/anchoredinterval.jl
src/description.jl
src/interval.jl
test/anchoredinterval.jl
test/inclusivity.jl
test/interval.jl
test/runtests.jl

This change allows the package to load on 0.7 and also fixes all deprecations emitted on 0.7.
...once it's done

Fix compatibility with Julia 0.7

---

src/Intervals.jl
src/interval.jl
test/comparisons.jl

- Add `superset` function that creates an interval which encompasses all of the intervals within an array
- ~Rename interval check functions to start with "is" (with deprecations)~
- Add `Interval` constructor which takes `Endpoint`s

Add superset function

---

src/anchoredinterval.jl
src/endpoint.jl
src/interval.jl
test/anchoredinterval.jl
test/comparisons.jl
test/endpoint.jl
test/interval.jl

Addresses this problem:
```julia
julia> using Intervals, TimeZones
julia> n = now(tz"America/Winnipeg")
2018-07-25T15:06:54.901-05:00
julia> a = Interval(n, n)
Interval{TimeZones.ZonedDateTime}(2018-07-25T15:06:54.901-05:00, 2018-07-25T15:06:54.901-05:00, Inclusivity(true, true))
julia> b = deepcopy(a)
Interval{TimeZones.ZonedDateTime}(2018-07-25T15:06:54.901-05:00, 2018-07-25T15:06:54.901-05:00, Inclusivity(true, true))
julia> hash(a) == hash(b)
false
julia> isequal(a, b)
true
```

Define hash methods

---

src/endpoint.jl
test/endpoint.jl

This fixes the "==" issue in #54 
Also adds the Left/Right consts. 
- Added == functions for (left,left), (right,right), (scalar,left),
(scalar, right), (left, scalar), (right, scalar)
- Added isequal functions for (left,left) and (right,right)
- Changed some functions to not be repetitions of previous code such as
Left == Right code will just call Right == Left instead of redefining
the same code within both functions.
- Added First = Left, and Last = Right shortcuts.
- Added some more Scalar tests because why not

Fix Scalar and Endpoint equality

---

src/interval.jl
test/interval.jl

Fixes: https://github.com/invenia/Intervals.jl/issues/60

Allow `in` with mixed types

---

.appveyor.yml
.travis.yml
REQUIRE
docs/make.jl
test/anchoredinterval.jl
test/interval.jl

In Julia v"1.2.0-DEV.29" Date and DateTime repr changed from
"yyyy-mm-dd" to "Date(yyyy, m, d)", and similarly with DateTime. This
changed that comes out of show, so the tests that check the output
string of Intervals with Dates and DateTimes had to be changed to follow
suit.
Closes #59

Modify tests for Date/DateTime repr changes

---

src/inclusivity.jl
src/interval.jl

Previously:
```julia
julia> import Intervals
julia> Intervals.Interval(1,2)
Interval{Int64}(1, 2, Inclusivity(true, true))
julia> Interval{Int64}(1, 2, Inclusivity(true, true))
ERROR: UndefVarError: Interval not defined
Stacktrace:
[1] top-level scope at none:0
```
PR:
```julia
julia> import Intervals
julia> Intervals.Interval(1,2)
Intervals.Interval{Int64}(1, 2, Intervals.Inclusivity(true, true))
julia> Intervals.Interval{Int64}(1, 2, Intervals.Inclusivity(true, true))
Intervals.Interval{Int64}(1, 2, Intervals.Inclusivity(true, true))
```

Show qualified type

---

test/anchoredinterval.jl
test/interval.jl

The changes introduced in https://github.com/JuliaLang/julia/pull/30817 were breaking our tests with the Julia nightly. Instead of adding an additional way of testing show I instead made the expected result for show dynamically created.
Continues the work done in: https://github.com/invenia/Intervals.jl/pull/64

Address show changes with periods on 1.2.0-DEV.223

---

Project.toml

Using `>=` in the Project.toml compat isn't great as a future version of TimeZones could be incompatible with this package.

Avoid using >= in compat

---

Project.toml

Follow up to #82  so I can tag release.
Got ot upper bound the versions.
I tested with 0.8 and 1.0
(interestingly TimeZones.jl is not compatible with 1.0 will make follow up for that,
but its incompatiability doesn't affect Intervals.jl)

specify compat for RecipeBase

---

Project.toml
src/Intervals.jl
src/anchoredinterval.jl
src/interval.jl
test/anchoredinterval.jl
test/interval.jl

So we can extract the timezone directly from the `Interval`
```julia
TimeZones.timezone(x::Interval{ZonedDateTime}) = timezone(first(x))
TimeZones.timezone(x::AnchoredInterval{P, ZonedDateTime}) where P = timezone(anchor(x))
```

Overload timezone

---

test/plotting.jl
test/runtests.jl

Reduces the time-to-failure. Previously it would take 43 seconds to reach the end of the comparisons tests where now it only takes 22 seconds.

Include plotting dependencies later

---

src/interval.jl
test/comparisons.jl
test/interval.jl

Adapted from https://github.com/invenia/Intervals.jl/pull/95. Takes the, hopefully, non-controversial parts of that PR and uses the `Float64` infinity to validate the changes.
@fchorney doing this allowed me to go very carefully through your tests. I've removed a few of them that are redundant with those which are in comparison.jl and some were re-worked to avoid code duplication.

Support intervals endpoints using infinity

---

src/Intervals.jl
src/anchoredinterval.jl
src/deprecated.jl
test/anchoredinterval.jl

Deprecated `convert` method as conversion [should be lossless](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Conversion-vs.-Construction-1). 
The additional constructor methods were removed as they are unnecessary and are not scale-able. For example we don't have a `ZonedDateTime(::AnchoredInterval)` constructor or constructors for subtypes of `Real`.

Deprecate invalid convert and unnecessary constructors

---

src/anchoredinterval.jl
src/deprecated.jl
src/interval.jl
test/anchoredinterval.jl

A continuation of https://github.com/invenia/Intervals.jl/pull/101. In that PR I deprecated `convert(::Type{T}, ::AnchoredInterval{P,T})` as the conversion was lossy. Recently I noticed `convert(::Type{T}, ::Interval{T})` which converts intervals with only a single element into a scalar. It appears that the `AnchoredInterval` version of this function was just implemented incorrectly.
Testing of deprecations:
```julia
julia> using Intervals, Dates
julia> Date(Interval(today(), today()))
┌ Warning: `Date(interval::Interval{Date})` is deprecated, use `convert(Date, interval)` instead.
│   caller = ip:0x0
└ @ Core :-1
2020-06-23
julia> DateTime(Interval(now(), now()))
┌ Warning: `DateTime(interval::Interval{DateTime})` is deprecated, use `convert(DateTime, interval)` instead.
│   caller = …
```

Fix AnchoredInterval scalar convert instead of deprecating

---

src/interval.jl
test/interval.jl

Adds deprecation for: https://github.com/invenia/Intervals.jl/issues/57

Deprecate reordering of Interval endpoints

---

src/anchoredinterval.jl
test/anchoredinterval.jl

I overlooked in https://github.com/invenia/Intervals.jl/pull/111 that I needed to have a deprecation when conversion was invalid.
Testing of deprecations
```julia
julia> using Intervals, Dates
julia> convert(DateTime, AnchoredInterval{Hour(0)}(DateTime(2000)))
2000-01-01T00:00:00
julia> convert(DateTime, HourEnding(DateTime(2000)))
┌ Warning: `convert(T, interval::AnchoredInterval{P,T})` is deprecated for intervals which are not closed with coinciding endpoints. Use `anchor(interval)` instead.
│   caller = top-level scope at REPL[3]:1
└ @ Core REPL[3]:1
2000-01-01T00:00:00
```

Add deprecation for old scalar convert

---

src/deprecated.jl
test/anchoredinterval.jl
test/interval.jl

Fixes:
```julia
MethodError: no method matching AnchoredInterval{-1 hour,LaxZonedDateTimes.LaxZonedDateTime,Open,Closed}(::LaxZonedDateTimes.LaxZonedDateTime, ::Inclusivity)
Closest candidates are:
AnchoredInterval{-1 hour,LaxZonedDateTimes.LaxZonedDateTime,Open,Closed}(::T) where {P, T, L<:Intervals.Bounded, R<:Intervals.Bounded} at /Users/admin/builds/f75a2375/0/invenia/BidPricing.jl.tmp/depot/packages/Intervals/jka4V/src/anchoredinterval.jl:72
AnchoredInterval{-1 hour,LaxZonedDateTimes.LaxZonedDateTime,Open,Closed}(::Any) where {P, T, L, R} at /Users/admin/builds/f75a2375/0/invenia/BidPricing.jl.tmp/depot/packages/Intervals/jka4V/src/anchoredinterval.jl:95
```
Gets called when writing generic functions. Examples of deprecation in action:
```julia
julia> using Intervals, Dates …
```

Add deprecation for full-type with inclusivity

---

src/deprecated.jl
test/anchoredinterval.jl
test/interval.jl

A constructor that doesn't seem to be used very often. Similar to: https://github.com/invenia/Intervals.jl/pull/114

Add deprecation for full-type convert with inclusivity

---

src/interval.jl
test/interval.jl

With bounded intervals we ensure that the lower/upper endpoint values are ordered correctly. Attempting to pass in `NaN` fails as isn't comparable with any other `Float64` including itself. When one of the endpoints is unbounded this check didn't occur which allowed `NaN` to be used as an endpoint value. Additionally, `nothing` should only be allowed as an endpoint value when the endpoint bound type is set to `Unbounded`. Having the `≤` check also enforces this but does so with a `MethodError` as `isless(::Nothing)` is not defined.

Ensure non-bounded intervals contain orderable endpoints

---

test/inclusivity.jl

Verifies that `Inclusivity` is deprecated and more importantly silences the deprecation warnings.
I may have noticed a bug with this and using `--depwarn=error` which I'll investigate separately.

Use `@test_deprecated` on Inclusivity

---

src/anchoredinterval.jl
test/anchoredinterval.jl

When updating `AnchoredInterval` with parametric bounds types the range function wasn't updated properly to allow for a `StepRange` to ever have an element type that was concrete. This in turn could cause issues with broadcasting resulting in non-backwards compatible behaviour.
Fixes: https://github.com/invenia/Intervals.jl/issues/122.

Use concrete eltype for AnchoredInterval StepRange

---

src/interval.jl

Intervals 1.2.0:
```julia
julia> using Intervals, TimeZones, BenchmarkTools
julia> zdt = ZonedDateTime(2000, 1, 1, tz"UTC")
2000-01-01T00:00:00+00:00
julia> @benchmark Interval{ZonedDateTime}($zdt, $zdt, $(Inclusivity(false, true)))
BenchmarkTools.Trial:
memory estimate:  32 bytes
allocs estimate:  1
--------------
minimum time:     7.507 ns (0.00% GC)
median time:      7.883 ns (0.00% GC)
mean time:        10.706 ns (9.95% GC)
maximum time:     1.757 μs (99.35% GC)
--------------
samples:          10000
evals/sample:     999
```
Intervals 1.3.3:
```julia
julia> using Intervals, TimeZones, BenchmarkTools
julia> zdt = ZonedDateTime(2000, 1, 1, tz"UTC")
2000-01-01T00:00:00+00:00
julia> @benchmark Interval{ZonedDateTime,Open,Closed}($zdt, $zdt)
BenchmarkTools.Trial:
memory estimate:  32 …
```

Improve `Interval` constructor performance

---

Project.toml
src/Intervals.jl
src/serialization.jl
test/anchoredinterval.jl
test/interval.jl
test/runtests.jl
test/test_utils.jl

Added to allow JLSO files saved with the older intervals structure to load transparently. Note that Julia serialization isn't guaranteed to work across versions of Julia but this should work on the same version of Julia with different versions of Intervals.

Support deserialize on previous interval structs

---

.travis.yml
docs/Manifest.toml
docs/make.jl
docs/src/index.md
src/anchoredinterval.jl
test/anchoredinterval.jl
test/runtests.jl

I noticed some printing tests were failing with Julia 1.6 so I fixed them and also needed to update the doctests. During process of updating the doctests I found that using filtering to make the doctests work on all version of Julia supported by this package would result in the date values just being ignored. To prevent that I decided to restrict the doctesting to just be on Julia 1.5 and 1.6 so that the doctests are actually still performing a reasonable amount of testing.

Restrict doctests to use Julia 1.5+

---

Project.toml

Tested locally on macOS that RecipesBase 0.7.0 passes tests. Note in order to use this version https://github.com/JuliaTime/TimeZones.jl/pull/280 is required.

Support RecipesBase 0.7

---

Project.toml
src/anchoredinterval.jl
test/anchoredinterval.jl
test/comparisons.jl
test/interval.jl
test/runtests.jl

Depends on https://github.com/cjdoris/Infinity.jl/pull/16 and https://github.com/cjdoris/Infinity.jl/pull/18 to be merged in.
This adds tests using Infinity.jl to confirm that it works with intervals.

Add tests using Infinity.jl

---

src/anchoredinterval.jl

add inclusivity default info to the docstrings for HourEnding and HourBeginning

---

src/compat.jl

Just cleaning up this serialization compatibility code. I'm a little more familiar with custom serialization now and this seemed to be a better approach.

Eliminate legacy serialization structs

---

src/Intervals.jl
src/anchoredinterval.jl
src/isfinite.jl
test/interval.jl
test/runtests.jl
test/test_utils.jl

As `isfinite(::Char)` is something that [isn't desired to be supported in Base](https://github.com/JuliaLang/julia/pull/36380#issuecomment-690646495) I'll refactor the Intervals.jl code to make internal support for this more reasonable.

Refactor generic `isfinite` support

---

src/docstrings.jl
src/interval.jl
src/isfinite.jl
test/anchoredinterval.jl
test/interval.jl

Create min/max functions that take bounds into account

---

README.md

Forgot to do this with the previous github actions PR.
Added the CI badge, and the JuliaNightly badge, but do we actually want the JuliaNightly badge to be on the README?

Add GHA badges to README

---

.github/workflows/CI.yml

Closes #172 
Solution suggested here: https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988
Official GR docs: https://gr-framework.org/workstations.html#no-output

Set GKSwtype env var to 100

---

docs/src/index.md
src/interval_sets.jl
test/sets.jl

This adds some documentation for `IntervalSets` and a test for the breaking behavior that lead  us to revert #175.
Also @omus, was there a reason you removed `find_intervals` from the docs? That's definitely one of the more useful functions I'm leveraging from the original PR. (I saw earlier that you remvoed it from the list of exports; not sure I understand that bit either but at the time didn't see a problem with an initial PR being that way, but I had missed that it was also removed from docs, so I'm wondering if you thought it was an implementation detail).
Another few notes:
- I've made it possible for `IntervalSet`'s field to be any `AbstractVector`. There are some cases where I have a view of `TimeSpan.jl` arrays that I want to be treated as `Interval.jl` arrays, I use an …

Tests, docs and some small fixes to IntervalSets

---

docs/src/index.md
src/interval_sets.jl

Found this error in the documentation. The documentation refers to the original design, implemented in #179 rather than the final design, as implemented in #196.

Correct set documentation

---

test/anchoredinterval.jl

Explicitly create a `StepRangeLen` for these tests instead of relying on `getindex` to return a `StepRangeLen`. This behaviour was changed in https://github.com/JuliaLang/julia/pull/43059

Fix `StepRangeLen` test

---

test/comparisons.jl

While reviewing #203 I was concerned about the small amount of testing done on `find_intersections`. This addition makes me more confident in that basic behaviours of `find_intersections` are working.

Add `find_intersections` to comparisons test suite

---

test/test_utils.jl

Silences the deprecation warnings added by https://github.com/invenia/Intervals.jl/pull/193 by testing for the deprecations.

Suppress deprecation warnings in tests
